// Surge local subscription output endpoint.
// Fetches the original universal subscription, converts ss:// + anytls:// to Surge proxy lines,
// stores the latest successful result, and falls back to that cache when upstream fails.
(function(){
'use strict';
var OUT='surge-subconverter-output-v1',STAT='surge-subconverter-status-v1';
function du(s){try{return decodeURIComponent(s)}catch(_){return s}}
function b64bytes(input){var s=String(input||'').replace(/\s+/g,'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';var a='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/',o=[],i,c1,c2,c3,c4,n;for(i=0;i<s.length;i+=4){c1=a.indexOf(s.charAt(i));c2=a.indexOf(s.charAt(i+1));c3=s.charAt(i+2)==='='?-1:a.indexOf(s.charAt(i+2));c4=s.charAt(i+3)==='='?-1:a.indexOf(s.charAt(i+3));if(c1<0||c2<0||(c3<0&&s.charAt(i+2)!=='=')||(c4<0&&s.charAt(i+3)!=='='))throw new Error('invalid base64');n=(c1<<18)|(c2<<12)|((c3<0?0:c3)<<6)|(c4<0?0:c4);o.push((n>>16)&255);if(c3>=0)o.push((n>>8)&255);if(c4>=0)o.push(n&255)}return o}
function utf8(b){var o='',i=0,b1,b2,b3,b4,cp;while(i<b.length){b1=b[i++];if(b1<128)o+=String.fromCharCode(b1);else if((b1&224)===192&&i<b.length){b2=b[i++];cp=((b1&31)<<6)|(b2&63);o+=String.fromCharCode(cp)}else if((b1&240)===224&&i+1<b.length){b2=b[i++];b3=b[i++];cp=((b1&15)<<12)|((b2&63)<<6)|(b3&63);o+=String.fromCharCode(cp)}else if((b1&248)===240&&i+2<b.length){b2=b[i++];b3=b[i++];b4=b[i++];cp=((b1&7)<<18)|((b2&63)<<12)|((b3&63)<<6)|(b4&63);cp-=65536;o+=String.fromCharCode(55296+(cp>>10),56320+(cp&1023))}else o+='�'}return o}
function b64(s){return utf8(b64bytes(s))}
function hasURI(s){return /(^|\r?\n)(ss|anytls):\/\//i.test(String(s||''))}
function decodeSub(s){s=String(s||'').trim();if(hasURI(s))return s;var d=b64(s);if(!hasURI(d))throw new Error('订阅不是受支持的 ss:// / anytls:// 通用订阅');return d}
function frag(u){var i=u.indexOf('#');return i<0?{body:u,name:''}:{body:u.slice(0,i),name:du(u.slice(i+1))}}
function query(s){var i=s.indexOf('?');return i<0?{body:s,query:''}:{body:s.slice(0,i),query:s.slice(i+1)}}
function qobj(q){var o={};if(!q)return o;q.split('&').forEach(function(p){if(!p)return;var i=p.indexOf('='),k=du(i<0?p:p.slice(0,i)),v=du(i<0?'':p.slice(i+1));if(!(k in o))o[k]=v});return o}
function hp(s){var h,p,i,e;if(s.charAt(0)==='['){e=s.indexOf(']');if(e<0||s.charAt(e+1)!==':')throw new Error('invalid IPv6 host:port');h=s.slice(1,e);p=Number(s.slice(e+2))}else{i=s.lastIndexOf(':');if(i<=0)throw new Error('missing port');h=s.slice(0,i);p=Number(s.slice(i+1))}if(!h||!p||p<1||p>65535)throw new Error('invalid host/port');return{host:h,port:p}}
function quote(v){v=String(v);return /[,"\r\n]|^\s|\s$/.test(v)?'"'+v.replace(/\\/g,'\\\\').replace(/"/g,'\\"')+'"':v}
function name(n,f){n=String(n||'').trim();return n||f}
function ss(uri,idx){var f=frag(uri),n=name(f.name,'SS-'+idx),r=query(f.body.slice(5)).body,a=r.lastIndexOf('@'),c,x;if(a>=0){var up=r.slice(0,a);try{c=b64(up)}catch(_){c=du(up)}x=hp(r.slice(a+1))}else{var d=b64(r),da=d.lastIndexOf('@');if(da<0)throw new Error('invalid SS URI');c=d.slice(0,da);x=hp(d.slice(da+1))}var co=c.indexOf(':');if(co<=0)throw new Error('invalid SS credential');var m=c.slice(0,co),pw=c.slice(co+1);if(!pw)throw new Error('empty SS password');return{name:n,protocol:'ss',line:n+' = ss, '+x.host+', '+x.port+', encrypt-method='+quote(m)+', password='+quote(pw)+', tfo=true, udp-relay=true'}}
function truth(v){return /^(1|true|yes|on)$/i.test(String(v||''))}
function anytls(uri,idx){var f=frag(uri),n=name(f.name,'AnyTLS-'+idx),r=query(f.body.slice(9)),a=r.body.lastIndexOf('@');if(a<=0)throw new Error('invalid AnyTLS URI');var pw=du(r.body.slice(0,a)),x=hp(r.body.slice(a+1)),q=qobj(r.query),ps=['password='+quote(pw)],sni=q.sni||q.peer||q.serverName||q.server_name;if(sni)ps.push('sni='+quote(sni));if(truth(q.insecure)||truth(q.allowInsecure)||truth(q['skip-cert-verify']))ps.push('skip-cert-verify=true');if(q.reuse!==undefined){if(/^(0|false|no|off)$/i.test(String(q.reuse)))ps.push('reuse=false');else if(truth(q.reuse))ps.push('reuse=true')}if(q.alpn)ps.push('alpn='+quote(q.alpn));return{name:n,protocol:'anytls',line:n+' = anytls, '+x.host+', '+x.port+', '+ps.join(', ')}}
function unique(it,seen){var b=it.name,n=b,i=2;while(seen[n])n=b+' #'+i++;seen[n]=1;if(n!==it.name){it.name=n;it.line=n+it.line.slice(it.line.indexOf(' ='))}return it}
function convertText(text){var ls=decodeSub(text).split(/\r?\n/),out=[],err=[],seen={},cnt={ss:0,anytls:0,ignored:0};ls.forEach(function(raw,i){var l=raw.trim();if(!l)return;try{var it;if(/^ss:\/\//i.test(l))it=ss(l,i+1);else if(/^anytls:\/\//i.test(l))it=anytls(l,i+1);else{cnt.ignored++;return}it=unique(it,seen);out.push(it.line);cnt[it.protocol]++}catch(e){err.push({index:i+1,reason:String(e&&e.message?e.message:e)})}});if(!out.length)throw new Error('没有转换出可用节点');return{output:out.join('\n'),total:out.length,ss:cnt.ss,anytls:cnt.anytls,ignored:cnt.ignored,failed:err.length,errors:err}}
function save(r){$persistentStore.write(r.output,OUT);$persistentStore.write(JSON.stringify({time:new Date().toISOString(),total:r.total,ss:r.ss,anytls:r.anytls,ignored:r.ignored,failed:r.failed}),STAT)}
function response(text,stale){var h={'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','X-Surge-Subscription-Studio':'1'};if(stale)h['X-Surge-Subscription-Stale']='1';return{response:{status:200,headers:h,body:String(text||'')}}}
function fail(text,status){return{response:{status:status||502,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'},body:String(text||'')}}}
function run(){var arg=String(typeof $argument!=='undefined'?($argument||''):'').trim();if(!/^https?:\/\//i.test(arg)){$done(fail('模块中没有配置有效的原始订阅 URL',500));return}$httpClient.get({url:arg,timeout:20,'auto-cookie':false},function(e,res,data){if(e||!data||(res&&res.status&&res.status>=400)){var c=$persistentStore.read(OUT);$done(c?response(c,true):fail('原始订阅请求失败，且没有可用缓存'));return}try{var r=convertText(data);save(r);$done(response(r.output,false))}catch(ex){var old=$persistentStore.read(OUT);$done(old?response(old,true):fail('订阅转换失败：'+String(ex&&ex.message?ex.message:ex)))}})}
if(typeof module!=='undefined'&&module.exports)module.exports={convertText:convertText};else run();
})();
