// Surge Subscription Studio: local UI + cached policy-path output.
// Conversion APIs are served by Scripts/subscription-converter.js and share the same persistent-store keys.
(function(){
'use strict';
var OUT='surge-subconverter-output-v1';
function pathOf(u){var p=String(u||'').replace(/^https?:\/\/[^/]+/i,'');return(p.split('?')[0]||'/')}
function reply(body,type,status){return{response:{status:status||200,headers:{'Content-Type':type||'text/plain; charset=utf-8','Cache-Control':'no-store'},body:String(body||'')}}}
function page(){return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark"><title>Surge Subscription Studio</title><style>'+ 
':root{font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","PingFang SC",sans-serif;color-scheme:light dark;--bg:#f6f7fb;--surface:rgba(255,255,255,.84);--surface2:rgba(255,255,255,.62);--text:#111827;--muted:#667085;--line:rgba(17,24,39,.08);--accent:#5b5cf0;--accent2:#8b5cf6;--good:#12a150;--bad:#e5484d;--shadow:0 16px 50px rgba(30,41,59,.09)}'+
'@media(prefers-color-scheme:dark){:root{--bg:#0b0e14;--surface:rgba(21,25,34,.86);--surface2:rgba(27,32,43,.64);--text:#f6f7fb;--muted:#9aa4b2;--line:rgba(255,255,255,.08);--shadow:0 18px 54px rgba(0,0,0,.28)}}'+
'*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 10% -6%,rgba(91,92,240,.19),transparent 32%),radial-gradient(circle at 92% 2%,rgba(139,92,246,.12),transparent 26%),var(--bg);color:var(--text);padding:env(safe-area-inset-top) 0 env(safe-area-inset-bottom)}'+
'.app{width:min(940px,100%);margin:auto;padding:18px 16px 40px}.top{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:8px 2px 20px}.brand{display:flex;align-items:center;gap:12px}.mark{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(145deg,var(--accent),var(--accent2));box-shadow:0 10px 24px rgba(91,92,240,.28);color:#fff;font-weight:800;font-size:18px}.brand h1{font-size:20px;line-height:1.1;margin:0;font-weight:760;letter-spacing:-.02em}.brand p{font-size:12px;color:var(--muted);margin:4px 0 0}.statuspill{display:flex;align-items:center;gap:7px;font-size:12px;color:var(--muted);white-space:nowrap}.dot{width:8px;height:8px;border-radius:50%;background:#a0a7b4}.dot.good{background:var(--good);box-shadow:0 0 0 4px rgba(18,161,80,.12)}'+
'.hero{position:relative;overflow:hidden;border:1px solid var(--line);background:linear-gradient(135deg,#5b5cf0,#7548c8);color:#fff;border-radius:26px;padding:24px;box-shadow:0 20px 48px rgba(91,92,240,.22)}.hero:after{content:"";position:absolute;width:220px;height:220px;border-radius:50%;right:-85px;top:-105px;background:rgba(255,255,255,.12)}.hero h2{font-size:26px;margin:0 0 8px;letter-spacing:-.03em}.hero p{margin:0;opacity:.84;font-size:14px;max-width:620px;line-height:1.55}.hero-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}'+
'button{font:inherit;appearance:none;border:0;cursor:pointer;border-radius:13px;padding:11px 14px;font-size:14px;font-weight:680;transition:transform .16s ease,opacity .16s ease}button:active{transform:scale(.98)}button:disabled{opacity:.5}.primary{background:#fff;color:#3f3fc6}.ghost{background:rgba(255,255,255,.14);color:#fff;border:1px solid rgba(255,255,255,.16)}.soft{background:var(--surface2);color:var(--text);border:1px solid var(--line)}'+
'.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:14px 0}.stat{padding:16px 15px;background:var(--surface);border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow);backdrop-filter:blur(18px)}.stat b{display:block;font-size:24px;line-height:1;font-weight:760;letter-spacing:-.03em}.stat span{display:block;color:var(--muted);font-size:11px;margin-top:7px}.goodtext{color:var(--good)}.badtext{color:var(--bad)}'+
'.section{margin-top:14px;background:var(--surface);border:1px solid var(--line);border-radius:22px;box-shadow:var(--shadow);backdrop-filter:blur(18px);overflow:hidden}.section-head{padding:17px 18px 10px;display:flex;align-items:center;justify-content:space-between;gap:10px}.section-head h3{font-size:15px;margin:0}.section-head small{color:var(--muted)}.subbox{padding:0 18px 18px}.urlrow{display:flex;align-items:center;gap:9px;background:var(--surface2);border:1px solid var(--line);border-radius:15px;padding:10px 10px 10px 13px}.url{flex:1;min-width:0;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--muted)}.mini{padding:8px 10px;border-radius:10px;background:var(--text);color:var(--bg);font-size:12px}.policy{margin-top:10px;padding:12px 13px;border-radius:14px;background:rgba(91,92,240,.07);border:1px solid rgba(91,92,240,.14);font:11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);overflow:auto;white-space:nowrap}'+
'.tools{padding:12px 18px;border-top:1px solid var(--line);display:flex;gap:10px;align-items:center;flex-wrap:wrap}.search{flex:1;min-width:190px;display:flex;align-items:center;gap:8px;background:var(--surface2);border:1px solid var(--line);border-radius:13px;padding:0 12px}.search input{width:100%;height:40px;border:0;outline:0;background:transparent;color:var(--text);font:inherit;font-size:13px}.seg{display:flex;gap:4px;padding:4px;border-radius:12px;background:var(--surface2);border:1px solid var(--line)}.seg button{padding:7px 10px;border-radius:9px;background:transparent;color:var(--muted);font-size:12px}.seg button.active{background:var(--text);color:var(--bg)}'+
'.nodes{border-top:1px solid var(--line);max-height:52vh;overflow:auto}.node{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:13px 18px;border-bottom:1px solid var(--line)}.node-name{font-size:13px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.node-meta{font-size:11px;color:var(--muted);margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tag{font-size:10px;font-weight:700;padding:5px 7px;border-radius:8px;background:rgba(91,92,240,.09);color:var(--accent);text-transform:uppercase}.empty{padding:34px 18px;text-align:center;color:var(--muted);font-size:13px}.footer{padding:18px 2px 0;text-align:center;color:var(--muted);font-size:11px}.toast{position:fixed;left:50%;bottom:max(22px,env(safe-area-inset-bottom));transform:translate(-50%,14px);opacity:0;pointer-events:none;background:rgba(20,23,31,.92);color:#fff;padding:10px 14px;border-radius:12px;font-size:12px;transition:.2s ease;z-index:20}.toast.show{opacity:1;transform:translate(-50%,0)}'+
'@media(max-width:620px){.app{padding:12px 12px 32px}.top{padding-bottom:14px}.brand h1{font-size:18px}.statuspill span:last-child{display:none}.hero{padding:21px;border-radius:22px}.hero h2{font-size:23px}.stats{grid-template-columns:repeat(2,1fr)}.section{border-radius:19px}.search{flex-basis:100%}.seg{width:100%}.seg button{flex:1}.section-head,.subbox,.tools{padding-left:15px;padding-right:15px}.node{padding:12px 15px}}'+
'</style></head><body><main class="app"><header class="top"><div class="brand"><div class="mark">S</div><div><h1>Subscription Studio</h1><p>Surge 本机订阅转换器</p></div></div><div class="statuspill"><i id="dot" class="dot"></i><span id="topStatus">读取中</span></div></header>'+
'<section class="hero"><h2>一个链接，直接给 Surge 用</h2><p>把原始通用订阅转换成 Surge 原生节点，并缓存为本机订阅输出。保留 Shadowsocks 与 AnyTLS，原始 Token 不显示在页面。</p><div class="hero-actions"><button id="convert" class="primary">刷新订阅</button><button id="copySubHero" class="ghost">复制订阅地址</button></div></section>'+
'<section class="stats"><div class="stat"><b id="total">-</b><span>总节点</span></div><div class="stat"><b id="ss">-</b><span>Shadowsocks</span></div><div class="stat"><b id="anytls">-</b><span>AnyTLS</span></div><div class="stat"><b id="failed">-</b><span>转换失败</span></div></section>'+
'<section class="section"><div class="section-head"><div><h3>新订阅输出</h3><small id="updated">等待首次转换</small></div><button id="copyPolicy" class="soft">复制配置</button></div><div class="subbox"><div class="urlrow"><div class="url">http://surge-converter.test/subscription</div><button id="copySub" class="mini">复制订阅地址</button></div><div class="policy">✈️ 我的节点 = select, policy-path=http://surge-converter.test/subscription, update-interval=1800</div></div>'+
'<div class="tools"><label class="search"><span>⌕</span><input id="search" type="search" placeholder="搜索节点名称或地址" autocomplete="off"></label><div class="seg"><button class="active" data-filter="all">全部</button><button data-filter="ss">SS</button><button data-filter="anytls">AnyTLS</button></div></div><div id="nodes" class="nodes"><div class="empty">正在载入节点…</div></div></section>'+
'<div class="footer">仅本机可用 · http://surge-converter.test/</div></main><div id="toast" class="toast">已复制</div><textarea id="clip" style="position:fixed;left:-9999px;top:-9999px"></textarea><script>'+ 
'const $=id=>document.getElementById(id),SUB="http://surge-converter.test/subscription",POLICY="✈️ 我的节点 = select, policy-path="+SUB+", update-interval=1800";let raw="",nodes=[],filter="all";'+
'async function json(u){const r=await fetch(u,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||("HTTP "+r.status));return j}'+
'function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1400)}'+
'async function copyText(t){try{await navigator.clipboard.writeText(t)}catch(_){const e=$("clip");e.value=t;e.focus();e.select();document.execCommand("copy")}toast("已复制")}'+
'function esc(s){return String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\\\"":"&quot;"}[c]||c))}'+
'function paint(s){$("total").textContent=s.total||0;$("ss").textContent=s.ss||0;$("anytls").textContent=s.anytls||0;$("failed").textContent=s.failed||0;$("failed").className=s.failed?"badtext":"goodtext";$("dot").className="dot "+(s.has_cache?"good":"");$("topStatus").textContent=s.has_cache?"订阅可用":"暂无缓存";$("updated").textContent=s.time?("更新于 "+new Date(s.time).toLocaleString()):"等待首次转换"}'+
'function parse(t){return t.split(/\n+/).map(l=>{const m=l.match(/^(.+?)\s*=\s*(ss|anytls),\s*([^,]+),\s*([^,]+)/i);return m?{name:m[1].trim(),type:m[2].toLowerCase(),host:m[3].trim(),port:m[4].trim()}:null}).filter(Boolean)}'+
'function render(){const q=$("search").value.trim().toLowerCase(),a=nodes.filter(n=>(filter==="all"||n.type===filter)&&(!q||(n.name+" "+n.host).toLowerCase().includes(q)));$("nodes").innerHTML=a.length?a.map(n=>`<div class="node"><div><div class="node-name">${esc(n.name)}</div><div class="node-meta">${esc(n.host)}:${esc(n.port)}</div></div><span class="tag">${n.type}</span></div>`).join(""):`<div class="empty">没有匹配的节点</div>`}'+
'async function load(){try{const r=await fetch("/api/output?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("暂无转换缓存");raw=await r.text();nodes=parse(raw);render()}catch(e){$("nodes").innerHTML=`<div class="empty">${esc(e.message)}</div>`}}'+
'async function status(){try{const s=await json("/api/status?ts="+Date.now());paint(s);return s}catch(e){$("topStatus").textContent="状态读取失败";return null}}'+
'async function convert(){const b=$("convert");b.disabled=true;b.textContent="转换中…";try{const s=await json("/api/convert?ts="+Date.now());paint(s);await load();toast("订阅已更新")}catch(e){toast("转换失败："+e.message)}finally{b.disabled=false;b.textContent="刷新订阅"}}'+
'$("convert").onclick=convert;$("copySub").onclick=$("copySubHero").onclick=()=>copyText(SUB);$("copyPolicy").onclick=()=>copyText(POLICY);$("search").oninput=render;document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;render()});status().then(s=>{if(s&&s.has_cache)load()});'+
'</script></body></html>'}
var p=pathOf($request&&$request.url);
if(p==='/'||p==='/index.html'){$done(reply(page(),'text/html; charset=utf-8'));return}
if(p==='/subscription'){var c=$persistentStore.read(OUT);if(c)$done(reply(c,'text/plain; charset=utf-8'));else $done(reply('暂无转换缓存，请先打开 Subscription Studio 点击“刷新订阅”。','text/plain; charset=utf-8',503));return}
$done(reply('Not Found','text/plain; charset=utf-8',404));
})();
